[package]
name = "hakana-str"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
indexmap = { version = "1.8.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rustc-hash = "1.1.0"