mod algebra_analyzer;
mod classlike_analyzer;
pub mod config;
pub mod custom_hook;
mod def_analyzer;
mod expr;
mod expression_analyzer;
pub mod file_analyzer;
mod formula_generator;
mod functionlike_analyzer;
mod reconciler;
pub mod scope_analyzer;
pub mod scope_context;
pub mod statements_analyzer;
mod stmt;
mod stmt_analyzer;
pub mod taint_analyzer;
pub mod typed_ast;
mod unused_variable_analyzer;
