name: Rust

on:
  push:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**', 'third-party/**', 'Cargo.toml', 'build.rs', 'init.sh', '.github/workflows/rust.yml']
  pull_request:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**', 'third-party/**', 'Cargo.toml', 'build.rs', 'init.sh', '.github/workflows/rust.yml']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'true'

    # Step to install OCaml compiler and dependencies
    - name: Install OCaml
      run: |
        sudo apt-get update
        sudo apt-get install -y ocaml opam
        opam init --disable-sandboxing -y
        eval $(opam env)
    - name: Install watchman
      run: |
        # last version before upstream CI stopped working
        curl -L --output watchman.deb https://github.com/facebook/watchman/releases/download/v2023.05.01.00/watchman_ubuntu22.04_v2023.05.01.00.deb
        echo "4a2c75809c56823180b7965a3fd9a68ffc0190149c8fd218a182ada08260d235 watchman.deb" | sha256sum -c
        sudo apt install -y ./watchman.deb
    
    - name: Init repository
      run: ./init.sh
    - name: Build & Run tests
      run: |
        cargo run --release --bin hakana test tests

        # run Rust unit tests
        cargo test --release --workspace
