name: Rust

on:
  push:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**', 'third-party/**', 'Cargo.toml', 'build.rs', 'init.sh', '.github/workflows/rust.yml']
  pull_request:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**', 'third-party/**', 'Cargo.toml', 'build.rs', 'init.sh']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Step to install OCaml compiler and dependencies
    - name: Install OCaml
      run: |
        sudo apt-get update
        sudo apt-get install -y ocaml opam
        opam init --disable-sandboxing -y
        eval $(opam env)

    - name: Build & Run tests
      run: ./init.sh && cargo run --release --bin hakana test tests
